version: "3.8"
services:
  server:
    container_name: parrot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/settings:/data/settings
